# Recommended VS Code extension:
# https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml

[part-1]
task-1 = 0x0000000000401810
task-2 = 0x0000000000401745
task-3 = 0x000000000040b680

[part-2]
task-4 = 0x15
task-5 = 24

[part-3]
task-6 = 0xdeadbeeeeeeeeeef
task-7 = [0xef, 0xee, 0xee, 0xee, 0xee, 0xbe, 0xad, 0xde]
